### ISSUE TITLE
Create DB with MySqlWorkbench

### ISSUE THREAD

**Issue by georgidemirev** [Klimentina/SurveyLab#10]
Create the database from the workbench according to the entities and the relation we have from the previous tasks.

**Comment by georgidemirev** [comment]
For review for the task, you will send me here (as comment) the script that you use for the db creation. 
After that i expect that you do a REVERSE ENGINEER (function in the workbench), and create visual db connections and tables.
for example: https://dataedo.com/asset/img/kb/db-tools/mysql_workbench/mysql_workbench_reverse_engineer_diagram.png

**Comment by Klimentina** [comment]
- create db;
-- create schema 'survey_lab' ;
- create tables:
-- CREATE TABLE `survey_lab`.`User` (
  `userId` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `createdOn` DATE NOT NULL,
  `password` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`userId`));
- create mapping between pollOption and user (many to many relation):
-- create table user_pollOpt_map (user_id int, 
                            pollOption_id int, 
                            primary key (user_id, pollOption_id), 
  foreign key (user_id) references User (userId),        
  foreign key (pollOption_id) references PollOption (pollOptionId));  
create index prop_idx on user_pollOpt_map (user_id);

**Comment by Klimentina** [comment]
add foreign key:
ALTER TABLE Poll
ADD FOREIGN KEY (user) REFERENCES User(userId);
ALTER TABLE PollOption
ADD FOREIGN KEY (ParentPollId) REFERENCES Poll(pollId);

**Comment by Klimentina** [comment]
CREATE TABLE `survey_lab`.`poll` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_on` TIMESTAMP NULL,
  `text` VARCHAR(45) NULL,
  `user_id` INT NULL,
  `completed` TINYINT NULL,
  `multiple_choice` TINYINT NULL,
  `expire_date` DATE NULL,
  PRIMARY KEY (`id`));

CREATE TABLE `survey_lab`.`pollOption` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_on` TIMESTAMP NULL,
  `text` VARCHAR(45) NULL,
  `number_of_votes` INT NULL,
  `poll_id` INT NULL,
  PRIMARY KEY (`id`));

ALTER TABLE poll
ADD FOREIGN KEY (user_id) REFERENCES user(id);
ALTER TABLE pollOption
ADD FOREIGN KEY (poll_id) REFERENCES poll(id);

create table poll_opt_user_rel (user_id int,
poll_option_id int,
primary key (user_id, poll_option_id),
foreign key (user_id) references user (id),
foreign key (poll_option_id) references pollOption(id));
create index prop_idx on poll_opt_user_rel (user_id);
